# Generated by Django 5.2.8 on 2025-11-18 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='주문자명')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='총 주문 금액')),
                ('status', models.CharField(choices=[('pending', '주문 접수'), ('confirmed', '주문 확인'), ('shipped', '배송 중'), ('delivered', '배송 완료'), ('cancelled', '주문 취소')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격')),
                ('stock', models.IntegerField(default=0, verbose_name='재고')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='상품 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='주문 당시 가격')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상세',
                'verbose_name_plural': '주문 상세',
            },
        ),
    ]
